//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardAdjust.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardAdjust.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   カード一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Header_CardList {
            get {
                return ResourceManager.GetString("Header_CardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレビュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Header_Preview {
            get {
                return ResourceManager.GetString("Header_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元画像 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Header_SourceImage {
            get {
                return ResourceManager.GetString("Header_SourceImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カードサイズ是正アプリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Title {
            get {
                return ResourceManager.GetString("Label_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   読取 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Read {
            get {
                return ResourceManager.GetString("Button_Read", resourceCulture);
            }
        }

        /// <summary>
        ///   調整 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Adjust {
            get {
                return ResourceManager.GetString("Button_Adjust", resourceCulture);
            }
        }

        /// <summary>
        ///   イラスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Illustration {
            get {
                return ResourceManager.GetString("Label_Illustration", resourceCulture);
            }
        }

        /// <summary>
        ///   キープする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RadioButton_KeepAspectRatio {
            get {
                return ResourceManager.GetString("RadioButton_KeepAspectRatio", resourceCulture);
            }
        }

        /// <summary>
        ///   キープしない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RadioButton_DontKeepAspectRatio {
            get {
                return ResourceManager.GetString("RadioButton_DontKeepAspectRatio", resourceCulture);
            }
        }

        /// <summary>
        ///   説明文 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_Description {
            get {
                return ResourceManager.GetString("Label_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   個別調整 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AdjustDialog_Title {
            get {
                return ResourceManager.GetString("AdjustDialog_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   フォント種類 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_FontFamily {
            get {
                return ResourceManager.GetString("Label_FontFamily", resourceCulture);
            }
        }

        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_FontSize {
            get {
                return ResourceManager.GetString("Label_FontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   文字間隔 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_LetterSpacing {
            get {
                return ResourceManager.GetString("Label_LetterSpacing", resourceCulture);
            }
        }

        /// <summary>
        ///   行間隔 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_LineSpacing {
            get {
                return ResourceManager.GetString("Label_LineSpacing", resourceCulture);
            }
        }

        /// <summary>
        ///   共通設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_CommonSetting {
            get {
                return ResourceManager.GetString("Label_CommonSetting", resourceCulture);
            }
        }

        /// <summary>
        ///   クリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }

        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }

        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   出力先フォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Label_BatchExportFolder {
            get {
                return ResourceManager.GetString("Label_BatchExportFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   一斉出力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_BatchExport {
            get {
                return ResourceManager.GetString("Button_BatchExport", resourceCulture);
            }
        }
    }
}
